### ISSUE TITLE
Put `as |var|` on its own line

### ISSUE THREAD

**Issue by EvgenyOrekhov** [mfeckie/handlebars-formatter#11]
Handlebars Formatter should put `as |var|` on its own line.

Current behavior:

```hbs
{{#modal
  title=modalTitle
  body=modalBody
  active=showModal
  class="modal" as |m|
}}
    {{m.body}}
{{/modal}}
```

Expected behavior:

```hbs
{{#modal
  title=modalTitle
  body=modalBody
  active=showModal
  class="modal"
  as |m|
}}
    {{m.body}}
{{/modal}}
```

**Comment by mfeckie** [comment]
Thanks for the feedback.  Unfortunately, this extension is only a wrapper for `prettier` and I have no control over how `prettier` handles this stuff.

Consider submitting the feedback here https://github.com/prettier/prettier/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+glimmer
