### ISSUE TITLE
If a line exceeds max length, always put every attribute on a separate line

### ISSUE THREAD

**Issue by EvgenyOrekhov** [mfeckie/handlebars-formatter#12]
If the only thing that doesn't fit on a line is `}}`, then the code should be reformatted to multiple lines.

Current behavior:

```hbs
        {{foo-table-header-cell data="Last Status" visibleSmallMediumLarge=true
        }}
```

Expected behavior:

```hbs
        {{foo-table-header-cell
          data="Last Status"
          visibleSmallMediumLarge=true
        }}
```

**Comment by mfeckie** [comment]
Thanks for the feedback.  Unfortunately, this extension is only a wrapper for `prettier` and I have no control over how `prettier` handles this stuff.

Consider submitting the feedback here https://github.com/prettier/prettier/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+glimmer
