### ISSUE TITLE
Preserve linebreaks

### ISSUE THREAD

**Issue by EvgenyOrekhov** [mfeckie/handlebars-formatter#13]
Example:

```hbs
<div></div>

{{bar}}
```

Current behavior:

```hbs
<div></div>{{bar}}
```

Expected behavior:

```hbs
<div></div>

{{bar}}
```

**Comment by mfeckie** [comment]
Thanks for the feedback.  Unfortunately, this extension is only a wrapper for `prettier` and I have no control over how `prettier` handles this stuff.

Consider submitting the feedback here https://github.com/prettier/prettier/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+glimmer
