### ISSUE TITLE
Disable formatting for particular lines

### ISSUE THREAD

**Issue by ArunimaSharma1909** [mfeckie/handlebars-formatter#15]
We need to have a way to disable formatting for particular lines.

For example, I need code to access Tool One from an object:
**Required Code**:  `data.[Tool One]`

However the formatter changes it to:
**Changed code**: `data.Tool
                                   One`

_This renders the code useless changing the whole functionality._

**Comment by mfeckie** [comment]
I have never tried such code.  If I needed something like that, I'd use the `get` template helper https://api.emberjs.com/ember/3.13/classes/Ember.Templates.helpers/methods/get?anchor=get

I think what you've shared is only working by accident as that's not recommended handlebars syntax.
