### ISSUE TITLE
Auto formatted double quote into single quote when there's an escape sign in the string

### ISSUE THREAD

**Issue by sophiaonion** [mfeckie/handlebars-formatter#16]
E.g. if I have {{help "Print this string with <div class=\"style\">"}} the prettier would auto format it  {{help 'Print this string with <div class="style">'}}

**Comment by mfeckie** [comment]
Thanks for the suggestion, unfortunately it's out of scope for this project.  This project is a wrapper for using https://prettier.io so can only do what is provided out of the box there.

Please consider making your request to the prettier team.
