### ISSUE TITLE
Tilde is formatted away when saving

### ISSUE THREAD

**Issue by gossi** [mfeckie/handlebars-formatter#18]
When you have a tilde inside curlies, they are formatted away when saving.

Before:

```
{{~@foo~}}
```

After:

```
{{@foo}}
```

Which is not an expected behavior.

**Comment by mfeckie** [comment]
Hi, thanks for the report. This extension is just a wrapper around `prettier` so the problem should be reported there. If it's already been addressed within prettier, then I can do a dependency bump.
