### ISSUE TITLE
prettier inline ignore syntax

### ISSUE THREAD

**Issue by danDanV1** [mfeckie/handlebars-formatter#19]
What's the correct syntax for inline ignore in hbs? 

I have tried the following from the [prettier docs](https://prettier.io/docs/en/ignore.html) without success.
`<!-- prettier-ignore -->`
`{{! prettier-ignore }}`

Is this an issue with the prettier glimmer parser? 

also, I found that the config from `.prettierignore` file isn't respected as well.

**Comment by mfeckie** [comment]
`{{! prettier-ignore }} ` should now be supported in the latest release

I haven't had chance to figure out how to make it respect `.prettierignore`
