### ISSUE TITLE
Doesn't work for some files

### ISSUE THREAD

**Issue by macgyver** [mfeckie/handlebars-formatter#2]
I created a really basic test file and the formatter works wonderfully there, but using it on some more complex files doesn't seem to do anything, I tried checking the Output panel but didn't see anything helpful in there. 

Here's some reduced input:
```hbs
<aside class="a" class="a" class="a" class="a" class="a" class="a" class="a" class="a" class="a"
  {{#if foo}}hidden{{/if}}
>
</aside>
```

the expected output would be
```hbs
<aside
  class="a"
  class="a"
  class="a"
  class="a"
  class="a"
  class="a"
  class="a"
  class="a"
  class="a"
  {{#if foo}}hidden{{/if}}
></aside>
```

but no formatting seems to occur. Can you help to debug or point me in the right direction? Thanks!

**Comment by macgyver** [comment]
It seems like using the block helper inside a tag is (one of) what's causing the problem .. my project is using handlebars 4.0, does glimmer alter the syntax?

_edit_ yep that seems to be the issue, when I use the [Glimmer Playground](https://try.glimmerjs.com/?app=JTdCJTIyY29tcG9uZW50cyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJHbGltbWVyQXBwJTIyJTJDJTIydGVtcGxhdGUlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRkdsaW1tZXJBcHAlMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTNDYXNpZGUlNUNuJTIwJTIwJTIwJTIwJTdCJTdCJTIzaWYlMjBmb28lN0QlN0RoaWRkZW4lN0IlN0IlMkZpZiU3RCU3RCU1Q24lM0UlNUNuJTNDJTJGYXNpZGUlM0UlNUNuJTIyJTdEJTJDJTIyY29tcG9uZW50JTIyJTNBJTdCJTIyZmlsZU5hbWUlMjIlM0ElMjJzcmMlMkZ1aSUyRmNvbXBvbmVudHMlMkZHbGltbWVyQXBwJTJGY29tcG9uZW50LnRzJTIyJTJDJTIyc291cmNlVGV4dCUyMiUzQSUyMmltcG9ydCUyMENvbXBvbmVudCUyQyUyMCU3QiUyMHRyYWNrZWQlMjAlN0QlMjBmcm9tJTIwJyU0MGdsaW1tZXIlMkZjb21wb25lbnQnJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyMGV4dGVuZHMlMjBDb21wb25lbnQlMjAlN0IlNUNuJTIwJTIwJTQwdHJhY2tlZCUyMGNvdW50JTIwJTNEJTIwMSUzQiU1Q24lMjAlMjBpbmNyZW1lbnQoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB0aGlzLmNvdW50JTJCJTJCJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlMjIlN0QlN0QlNUQlMkMlMjJoZWxwZXJzJTIyJTNBJTVCJTVEJTdE) I see the error 
>Error: A block may only be used inside an HTML element or another block.

It's kind of hard to understand the relationship between Glimmer and Handlebars - is this a bug or does this plugin just not completely work for classic handlebars?

**Comment by mfeckie** [comment]
Sorry for the late reply.  This extension relies on the handlebars formatter in `prettier`, it does not seem to handle the example you have shared.

Should the underlying implementation ever handle your example, I can update this extension, but otherwise I can't really see a good solution.

May be worth filing and issue with the prettier project.
