### ISSUE TITLE
Any recommendations re bulk formatting?

### ISSUE THREAD

**Issue by janice-hashicorp** [mfeckie/handlebars-formatter#23]
Is there means to run this formatter via the command line to reformat all files with a particular directory? I've attempted something along the lines of `"prettier-eslint --write --config ../../.prettierrc 'app/templates/*.hbs' 'app/templates/**/*.hbs'"`, but received the  `No parser could be inferred for file` error. 

Any recommendations? 

**`package.json`**
Under `scripts`: 
`fmtH: "prettier-eslint --write --config ../../.prettierrc 'app/templates/*.hbs' 'app/templates/**/*.hbs'",`

**`.prettierrc`**

```
{
   ..."overrides": [
  {
      "files": "*.hbs",
      "options": {
        "singleQuote": false,
        "plugins": ["handlebars-formatter"]
      }
    }
  ]
}

//Tried with and without plugins.

**Comment by mfeckie** [comment]
I'm not familiar with how prettier-eslint works, but this extension uses `prettier` directly under the hood.

I _think_ in your `.prettierrc` you would want to set the parse https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option .  The parser needed is called `glimmer`.  It's currently unreleased but part of `prettier`.

You can run it via terminal if you have `prettier` install globally or as part of your `package.json`

`yarn run prettier --parser glimmer ./app/templates/**/*.hbs` is the invocation.  If you want to actually write the changes then `yarn run prettier --parser glimmer --write ./app/templates/**/*.hbs`

**Comment by mfeckie** [comment]
I'm gonna close this issue now as it's not specific to the extension.  Hopefully the response is helpful.

**Comment by janice-hashicorp** [comment]
Worked perfectly! (No need to reopen, just wanted to express my thanks!)
