### ISSUE TITLE
Unicode html entitles get stripped when they shouldn't

### ISSUE THREAD

**Issue by jpike88** [mfeckie/handlebars-formatter#24]
try formatting this:

```
<span class="stampFont" style="font-family: 'stampfont'">&#xf000;</span>
```

That entity is valid HTML and shouldn't be stripped... but it gets changed to this:

```
<span class="stampFont" style="font-family: 'stampfont'">
  
</span>
```

**Comment by mfeckie** [comment]
Hi @jpike88 unfortunately this is a problem with Prettier, I can't do anything to resolve it here.  Please consider filing and issue with the Prettier project.

If it gets resolved upstream, I'm happy to update the version of prettier being used by this addon.

**Comment by jpike88** [comment]
It's been fixed upstream but there's been no release for prettier yet...

**Comment by mfeckie** [comment]
It's possible to use prettier now without this extension, which may allow you to use a custom version. https://dev.to/jelhan/format-glimmer-templates-with-prettier-ipa

I'm happy to update here once a proper release of prettier is out.
