### ISSUE TITLE
Expanding non block elements to block causes bugs

### ISSUE THREAD

**Issue by taras** [mfeckie/handlebars-formatter#4]
Thank you for making this extension. It's very useful.

The only problem that I found with using this extension is that converts non block html element to block syntax. For example, formatting `<HelloWorld />` will convert it to `<HelloWorld></HelloWorld>`. This will introduce bugs to Ember app that has components which detect block syntax.

The behaviour of block vs non block component can be very different. I would not expect the formatter to change the behaviour of my code.

**Comment by mfeckie** [comment]
This extension relies on the underlying implementation of handlebars formatting in `prettier`.

I've bumped to the latest version of `prettier` and it seems to work with your example correctly now.

See if updating the extension to `0.0.3` addresses your issue.

Reopen if it does not 😄
