### ISSUE TITLE
Typo in provideDocumentRangeFormattingEdits

### ISSUE THREAD

**Issue by jeff-kilbride** [mfeckie/handlebars-formatter#5]
Thanks! Would love to get this working.

https://github.com/mfeckie/handlebars-formatter/blob/67c9ba3c3469d9565bb7028ad0919695aeb400bd/src/extension.ts#L25

I believe this should be `glimmer`.

Also, it doesn't seem to be doing anything even after fixing this locally. When I use `Format Document`, there is no change and when I use `Format Selection`, it seems to format like normal HTML.

Could it be the new v15.x of prettier?

**Comment by mfeckie** [comment]
I'm really not sure how to fix this issue.  I've tried adding a `registerDocumentRangeFormattingEditProvider` as per https://code.visualstudio.com/docs/extensionAPI/vscode-api, but that doesn't ever get triggered.

It seems like something else is taking priority for selection formatting in handlebars and I have no idea how to fix that.

I'd be happy to accept a PR though!

**Comment by jeff-kilbride** [comment]
For now, I'm using the new html formatting ability in `prettier` to handle things. Hopefully, their official `glimmer` support will come along soon.

Thanks.
