### ISSUE TITLE
4 spaces instead of 2

### ISSUE THREAD

**Issue by yairEO** [mfeckie/handlebars-formatter#7]
How can this be done?

Thank you

Root `.prettierrc` file:

```
{
	"singleQuote"        : true,
	"printWidth"         : 80,
	"editor.formatOnSave": true,
	"proseWrap"          : "always",
	"tabWidth"           : 4,               <------- 
	"requireConfig"      : false,
	"useTabs"            : false,
	"trailingComma"      : "none",
	"bracketSpacing"     : true,
	"jsxBracketSameLine" : false,
	"semi"               : true
}
```

**Comment by mfeckie** [comment]
I've never needed to make changes to the base settings, but I think it should be possible.

It's not something I have time to work on, so if you want this change I'd be happy to accept a PR with the necessary changes.

Probably somewhere around here https://github.com/mfeckie/handlebars-formatter/blob/master/src/extension.ts#L24 to refer to prettierrc

I'm not sure about how prettier deals with defaults and overrides

**Comment by mfeckie** [comment]
I'm going to close this issue as stale
