### ISSUE TITLE
Disable html entity conversion

### ISSUE THREAD

**Issue by billdami** [mfeckie/handlebars-formatter#8]
Is there a way to disable prettier's automatic conversion of html entity codes into their rendered values? For instance, `&nbsp;` gets converted into a literal space, but that is not always semantically or visually equivalent (i.e. when multiple adjacent literal spaces are collapsed into one in the DOM).

**Comment by mfeckie** [comment]
I don't I'm afraid.  I've also got some issues with `prettier` collapsing nested `if` statements into incorrect `else if`s.

I haven't had a huge amount of time to look at this stuff recently, but will try and see if the upstream prettier `glimmer` support has improved

**Comment by mfeckie** [comment]
Looks like there's an open PR to fix this issue https://github.com/prettier/prettier/pull/4533

**Comment by billdami** [comment]
Ok, thanks for checking! I left a comment on that PR too, as it looks like it has gotten pretty stale.

**Comment by mfeckie** [comment]
I'm going to close the issue as it's a prettier concern.
